version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brandless_backend
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - database
      - redis
    environment:
      - APP_NAME=BrandlessCMS
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=brandless_cms
      - DB_USERNAME=brandless_user
      - DB_PASSWORD=brandless_password
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - SANCTUM_STATEFUL_DOMAINS=localhost:3000,localhost:3001
      - SESSION_DOMAIN=localhost
    networks:
      - brandless_shared_network

  database:
    image: mysql:8.0
    container_name: brandless_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=brandless_cms
      - MYSQL_USER=brandless_user
      - MYSQL_PASSWORD=brandless_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - brandless_shared_network

  redis:
    image: redis:7-alpine
    container_name: brandless_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - brandless_shared_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: brandless_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=database
      - PMA_USER=brandless_user
      - PMA_PASSWORD=brandless_password
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - database
    networks:
      - brandless_shared_network

volumes:
  database_data:
  redis_data:

networks:
  brandless_shared_network:
    external: true
